# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDKitSwift_UserDefaultManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDKitSwift_UserDefaultManager
	pod 'DDKitSwift/core', '~> 3.0.0'
	pod 'DDUserDefaultManager', '~> 3.0.0'
end
