# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'userDefaultManager-zxkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for userDefaultManager-zxkit
	pod 'ZXKitCore', '~> 2.0.0'
	pod 'ZXUserDefaultManager', '~> 2.0.0'
end
